# Generated by Django 5.1.2 on 2025-11-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
